title: The Narrated Life 2.0
author: Francesca Anastatsia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Place where I vocalize my observations, cogitations, and ideations
# social links
twitter_username: anyaii # DO NOT include the @ character, or else the build will fail!
github_username:  anyaii # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
